const {
  json,
  requestIdFromEvent,
  requirePermission,
  supabaseAdminRequest,
  writeAuditLog
} = require("./lib/dashboard-auth");

const STAGES = [
  "sales_intake", "sales_intake",
  "scope_in_progress", "scope_in_progress",
  "quote_pending", "quote_pending",
  "customer_approval_pending", "customer_approval_pending",
  "needs_budget", "needs_budget",
  "budget_in_progress", "budget_in_progress",
  "needs_owner_approval", "invoice_preparation", "ready_to_schedule",
  "scheduled", "in_progress", "completion_review", "closed", "closed"
];

const SERVICES = [
  "Seasonal grounds audit", "Entry bed refresh", "Shrub pruning", "Mulch installation",
  "Trash enclosure cleanup", "Storm debris pickup", "Irrigation observation", "Property walkthrough",
  "Leaf removal", "Curb appeal cleanup"
];

function dateOffset(days) {
  const date = new Date();
  date.setUTCDate(date.getUTCDate() + days);
  return date.toISOString().slice(0, 10);
}

function ticketState(stage, index, invoiceId = null) {
  const stageIndex = STAGES.indexOf(stage);
  const scopeComplete = stageIndex >= 2;
  const customerApproval = stageIndex >= 8;
  const costReview = stageIndex >= 12;
  const ownerApproval = stageIndex >= 13;
  const scheduled = stageIndex >= 15;
  const workStarted = stageIndex >= 16;
  const completion = stageIndex >= 17;
  const closed = stage === "closed";
  return {
    ticket_number: `QA-${String(index + 1).padStart(3, "0")}`,
    title: `TEST – CODEX QA – ${SERVICES[index % SERVICES.length]}`,
    stage,
    status: closed ? "completed" : ["scheduled", "in_progress"].includes(stage) ? "active" : "open",
    source_type: "ticket",
    customer_name: `TEST – Mock Client ${String(index + 1).padStart(2, "0")}`,
    contact_name: `QA Contact ${String(index + 1).padStart(2, "0")}`,
    property_name: `TEST – Mock Property ${String(index + 1).padStart(2, "0")}`,
    property_address: `${1100 + index} Test Route, Portland, OR`,
    city: "Portland",
    requested_service: SERVICES[index % SERVICES.length],
    service: SERVICES[index % SERVICES.length],
    scope_of_work: `QA-only property care scenario ${index + 1}. No real customer contact or external delivery.`,
    description: `TEST DATA – exercises ${stage.replace(/_/g, " ")} workflow behavior.`,
    internal_notes: "Generated by the owner-authorized Codex live QA suite. Do not contact externally.",
    proposed_price: 450 + index * 75,
    expected_revenue: scopeComplete ? 450 + index * 75 : null,
    estimated_total_cost: costReview ? 250 + index * 35 : null,
    estimated_profit: costReview ? 200 + index * 40 : null,
    target_margin: costReview ? 40 : null,
    scope_complete: scopeComplete,
    customer_approval_recorded: customerApproval,
    cost_review_complete: costReview,
    budget_complete: costReview,
    owner_approval_recorded: ownerApproval,
    invoice_id: invoiceId,
    draft_invoice_exists: Boolean(invoiceId),
    scheduled_date: scheduled ? dateOffset(index - 8) : null,
    visit_date: scheduled ? dateOffset(index - 8) : null,
    due_date: dateOffset(index - 4),
    responsible_role: closed ? "owner" : stage.includes("budget") || stage.includes("invoice") ? "accountant" : scheduled ? "field_worker" : "sales_outreach",
    owner_label: closed ? "Owner" : stage.includes("budget") || stage.includes("invoice") ? "Money" : scheduled ? "Work" : "Leads",
    next_action: closed ? "Completed" : `Continue ${stage.replace(/_/g, " ")}`,
    blockers: closed ? [] : completion ? ["Invoice review"] : [],
    before_photos_uploaded: workStarted,
    after_photos_uploaded: completion,
    arrival_photos_uploaded: workStarted,
    completion_photos_uploaded: completion,
    required_documents_present: completion,
    field_completion_notes: completion ? "QA work completed and internally reviewed." : null,
    invoice_finalized: closed,
    payment_status: closed ? "paid" : invoiceId ? "sent" : null
  };
}

exports.handler = async (event) => {
  const requestId = requestIdFromEvent(event);
  if (event.httpMethod !== "POST") return json(405, { error: "Method not allowed.", requestId });
  const auth = await requirePermission(event, "admin:manage", { entityType: "qa_seed" });
  if (!auth.ok) return json(auth.statusCode, { error: auth.error, requestId });

  let body = {};
  try { body = JSON.parse(event.body || "{}"); } catch {}
  if (body.confirmation !== "CREATE 20 MOCK TICKETS") return json(400, { error: "Invalid QA confirmation.", requestId });

  const existing = await supabaseAdminRequest("job_tickets?ticket_number=like.QA-*&select=id&limit=1", { method: "GET" });
  if (Array.isArray(existing) && existing.length) return json(409, { error: "QA tickets already exist. Reset them before reseeding.", requestId });

  const invoiceDocs = STAGES.map((stage, index) => ({ stage, index }))
    .filter(({ stage }) => ["invoice_preparation", "ready_to_schedule", "scheduled", "in_progress", "completion_review", "closed"].includes(stage))
    .map(({ stage, index }) => ({
      document_type: "invoice",
      document_number: `QA-INV-${String(index + 1).padStart(3, "0")}`,
      client_name: `TEST – Mock Client ${String(index + 1).padStart(2, "0")}`,
      client_email: null,
      issue_date: dateOffset(-2),
      due_date: dateOffset(14),
      status: stage === "closed" ? "paid" : stage === "invoice_preparation" ? "draft" : "sent",
      line_items: [{ description: SERVICES[index % SERVICES.length], quantity: 1, unit_price: 450 + index * 75, amount: 450 + index * 75 }],
      subtotal: 450 + index * 75,
      tax: 0,
      total: 450 + index * 75,
      notes: "QA-only invoice. Never send or sync to Square."
    }));

  const createdDocs = await supabaseAdminRequest("sales_documents", {
    method: "POST", headers: { Prefer: "return=representation" }, body: JSON.stringify(invoiceDocs)
  });
  let documentCursor = 0;
  const tickets = STAGES.map((stage, index) => {
    const needsInvoice = ["invoice_preparation", "ready_to_schedule", "scheduled", "in_progress", "completion_review", "closed"].includes(stage);
    const invoiceId = needsInvoice ? createdDocs[documentCursor++]?.id || null : null;
    return ticketState(stage, index, invoiceId);
  });
  const createdTickets = await supabaseAdminRequest("job_tickets", {
    method: "POST", headers: { Prefer: "return=representation" }, body: JSON.stringify(tickets)
  });

  const routeTickets = createdTickets.filter((ticket) => ["scheduled", "in_progress", "completion_review", "closed"].includes(ticket.stage));
  const routeStops = routeTickets.map((ticket, index) => ({
    route_date: ticket.scheduled_date || dateOffset(index),
    client_name: ticket.customer_name,
    address: ticket.property_address,
    service_type: ticket.service,
    estimated_minutes: 60 + index * 15,
    notes: `${ticket.ticket_number} QA route stop`,
    status: ticket.stage === "closed" ? "Complete" : ticket.stage === "in_progress" ? "In Progress" : "Planned",
    stop_order: index + 1
  }));
  await supabaseAdminRequest("route_stops", {
    method: "POST", headers: { Prefer: "return=minimal" }, body: JSON.stringify(routeStops)
  });

  const events = createdTickets.map((ticket) => ({
    ticket_id: ticket.id,
    event_type: "qa_ticket_seeded",
    to_stage: ticket.stage,
    notes: "Owner-authorized mock ticket generated for live workflow testing.",
    new_value: { qa: true, stage: ticket.stage }
  }));
  await supabaseAdminRequest("job_ticket_events", {
    method: "POST", headers: { Prefer: "return=minimal" }, body: JSON.stringify(events)
  });

  await writeAuditLog({
    actor: auth.actor, action: "qa_ticket_suite_created", entityType: "job_tickets",
    metadata: { tickets: createdTickets.length, invoices: createdDocs.length, routeStops: routeStops.length },
    event, module: "tickets"
  });
  return json(200, { tickets: createdTickets.length, invoices: createdDocs.length, routeStops: routeStops.length, requestId });
};

